# .streamlit/config.toml

[theme]
primaryColor="#4A90E2"  # Màu xanh nhạt cho phông chữ
backgroundColor="#E0F7FA"  # Xanh nhạt
secondaryBackgroundColor="#FFFFFF"  # Trắng nhạt cho nền phụ (sidebar)
textColor="#333333"  # Màu chữ xám đậm
font="sans serif"
